### ISSUE TITLE
Method not found: GetDefaultSerializerSettings()

### ISSUE THREAD

**Issue by pkese** [OrleansContrib/Orleans.Providers.MongoDB#14] opened 2017-07-09 14:56 UTC
I've been trying to use MongoDB provider, but I'm getting the following exception at initialization...

```
Method not found: 'Newtonsoft.Json.JsonSerializerSettings Orleans.Serialization.OrleansJsonSerializer.GetDefaultSerializerSettings()'.
Exception = System.MissingMethodException: Method not found: 'Newtonsoft.Json.JsonSerializerSettings Orleans.Serialization.OrleansJsonSerializer.GetDefaultSerializerSettings()'.
   at Orleans.Providers.MongoDB.StorageProviders.BaseJSONStorageProvider.Init(String name, IProviderRuntime providerRuntime, IProviderConfiguration config)
   at Orleans.Providers.ProviderLoader`1.<InitProviders>d__7.MoveNext()

[2017-07-09 14:36:05.172 GMT    38      ERROR   103109  ProviderLoader/IStorageProvider 192.168.11.2:11111]     !!!!!!!!!! Exception initializing provider Name=MongoStore Type=[MongoStore, Orleans.Providers.MongoDB.StorageProviders.MongoDBStorage]
Exc level 0: System.MissingMethodException: Method not found: 'Newtonsoft.Json.JsonSerializerSettings Orleans.Serialization.OrleansJsonSerializer.GetDefaultSerializerSettings()'.
   at Orleans.Providers.MongoDB.StorageProviders.BaseJSONStorageProvider.Init(String name, IProviderRuntime providerRuntime, IProviderConfiguration config)
   at Orleans.Providers.ProviderLoader`1.<InitProviders>d__7.MoveNext()
One or more errors occurred.
```

I'm using the default `Orleans.Providers.MongoDB` version (0.0.9) from NuGet, and Orleans 1.5.0.

I can not explain the error. The method should be there (it is clearly defined in Orleans 1.5's `OrleansJsonSerializer`)

Has anyone ever experienced a similar error?

Any ideas?

**Comment by pkese** [comment] 2017-07-09 15:31
Each time, after installing Orleans.Providers.MongoDB 0.0.9 from nuget,  
the version of the .dll on (in file properties) says it is 0.0.0.8.

I've tried to delete nuget caches, etc. but each time the .dll file is 0.0.0.8 from June 26th.

**Comment by pkese** [comment] 2017-07-09 15:37
Ah... `Properties/AssemblyInfo.cs` hasn't been updated.

So I'm having the latest .dll but the initial problem still persists.

**Comment by laredoza** [comment] 2017-07-09 18:33
Hi, my apologies I didn't up the dll number. Will fix that. There seems to be a lot of breaking changed in orleans 1.5. I thought I had some time to fix it but I see it was released on the 6th. Let me have a quick look.

Will get back to you.

**Comment by laredoza** [comment] 2017-07-09 19:38
I've started updating the project to Orleans 1.5. I've also updated the projects to 4.6.1. 

I can confirm that there are several issues.:

StorageProvider uses GetDefaultSerializerSettings which now requires several parameters instead of none.

Reminder service uses GrainReference.FromKeyString which is now internal. There is an issue for this one.

**Comment by laredoza** [comment] 2017-07-09 21:36
@pkese, There is a new package which fixes this issue. Let me know if you have any other issues. This was done in a bit of a hurry.

**Comment by ReubenBond** [comment] 2017-07-09 21:41
@laredoza I'll take a look at that FromKeyString issue today and come up with an alternative

**Comment by laredoza** [comment] 2017-07-16 16:26
I'm going to close this issue now. If there are any other issues please let me know.

**Comment by jamescarter-le** [comment] 2017-07-29 11:05
Thanks for fixing this issue - are you able to publish a new NuGet package with these changes?

Version 0.1.0 on Nuget has the old code, and the assembly is marked as 0.0.0.8:

```
public virtual Task Init(string name, IProviderRuntime providerRuntime, IProviderConfiguration config)
    {
      this.Log = providerRuntime.GetLogger(this.GetType().FullName);
      this.serializerSettings = OrleansJsonSerializer.GetDefaultSerializerSettings();
      return TaskDone.get_Done();
    }
```

**Comment by laredoza** [comment] 2017-07-29 11:52
As far as I know this issue is fixed by 0.1.0. I will have a quick look and get back to you.

**Comment by laredoza** [comment] 2017-07-29 12:26
My apologies, I'll have to improve my package generation script. I've uploaded a new package version. https://www.nuget.org/packages/Orleans.Providers.MongoDB/0.1.1

**Comment by jamescarter-le** [comment] 2017-07-29 12:34
@laredoza Thank you very much for pushing an updated version - grateful for this package and your work on it 👍

**Comment by laredoza** [comment] 2017-07-29 12:47
Thanks @jamescarter-le. Please let me know if you find any more issues.

**Closed by laredoza** 2017-07-29 12:47 UTC
